title: Gear Gurus
description: "August 2023 to June 2024"
owner_name: Aniket Chakradeo
github_username: AniCricKet
github_repo: "gear-gurus2.0"
baseurl: "/gear-gurus2.0"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/AniCricKet"}
    - { platform: github, user_url: "https://github.com/Soham360"}
    - { platform: github, user_url: "https://github.com/EdwinKuttappi"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
